import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import './About.css'

const principles = [
  {
    n: '01',
    title: 'Precision',
    body:
      'Every decision is deliberate. Interfaces, models, and systems perform exactly as intended — without excess and without ambiguity.',
  },
  {
    n: '02',
    title: 'Velocity',
    body:
      'Speed of execution without sacrificing quality. We ship, we iterate, and we close the distance between insight and product.',
  },
  {
    n: '03',
    title: 'Ambition',
    body:
      'We pursue work that matters. Not small problems that scale, but meaningful asymmetries where intelligence changes the outcome.',
  },
  {
    n: '04',
    title: 'Clarity',
    body:
      'Complexity is the enemy of trust. We strip systems down to what is legible — then let the remaining work be obvious.',
  },
]

const facts = [
  { label: 'Founded', value: '2026', sub: 'Volume I' },
  { label: 'Projects', value: '02', sub: 'Active now' },
  { label: 'Studio', value: 'Madrid', sub: 'Remote-first' },
  { label: 'Posture', value: 'AI-first', sub: 'Since day one' },
]

export default function About() {
  return (
    <motion.div
      className="page about"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.4 }}
    >
      {/* ── Hero ─────────────────────────────────────── */}
      <section className="shell about-hero">
        <div className="about-hero-top">
          <span className="eyebrow">§ 01 — Studio note</span>
          <span className="about-hero-date">MMXXVI / Vol. I</span>
        </div>

        <motion.h1
          className="display about-title"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, ease: [0.16, 1, 0.3, 1], delay: 0.1 }}
        >
          We build what
          <br />
          <em>doesn't</em> exist
          <br />
          <span className="accent">yet.</span>
        </motion.h1>

        <div className="about-hero-grid">
          <motion.div
            className="about-lede"
            initial={{ opacity: 0, y: 18 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.35, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            <p className="prose-lg">
              Project Odyssey is an AI-first studio. We build intelligent
              products where the gap between available data and human
              understanding is largest.
            </p>
            <p className="prose prose-sm">
              Sport is our first and largest front. The volume of data
              generated by modern football is enormous; the tools to make
              sense of it, for fans and organisations alike, are still
              catching up. We're closing that gap — deliberately, and in
              public.
            </p>
          </motion.div>

          <motion.aside
            className="about-facts"
            initial={{ opacity: 0, y: 18 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.45, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            {facts.map((f) => (
              <div key={f.label} className="about-fact">
                <span className="about-fact-label">{f.label}</span>
                <span className="about-fact-value">{f.value}</span>
                <span className="about-fact-sub">{f.sub}</span>
              </div>
            ))}
          </motion.aside>
        </div>
      </section>

      {/* ── Mission — long-form editorial ─────────── */}
      <section className="shell mission-wrap">
        <motion.header
          className="section-head"
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          <h2 className="section-head-title">
            An <em>odyssey</em>, <br />by design.
          </h2>
          <div className="section-head-meta">
            <span>§ 02 — The name, the mission</span>
            <span>A long journey — uncertain, difficult, defining</span>
          </div>
        </motion.header>

        <div className="mission-grid">
          <motion.div
            className="mission-col"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
          >
            <span className="mission-drop">O</span>
            <p className="mission-text">
              An odyssey is a long journey — one that is difficult,
              uncertain, and ultimately defining. Ours is about making
              artificial intelligence the foundation of every product we
              build, in every domain we enter.
            </p>
            <p className="mission-text">
              Sport is where the asymmetry is most dramatic. The volume of
              data generated by modern football is enormous; the tools to
              make sense of it, for fans and organisations alike, are still
              catching up. We're building those tools — and the approach
              scales anywhere the same gap exists.
            </p>
            <p className="mission-text">
              We don't chase trends. We pursue problems where intelligence,
              applied deliberately, changes the outcome.
            </p>
          </motion.div>

          <motion.aside
            className="mission-pull"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 1, ease: [0.16, 1, 0.3, 1], delay: 0.1 }}
          >
            <span className="mission-pull-mark">§</span>
            <p className="mission-pull-text">
              "We build intelligent products where the gap between
              available data and human understanding is <em>largest</em>."
            </p>
            <span className="mission-pull-attribution">— Studio position</span>
          </motion.aside>
        </div>
      </section>

      {/* ── Principles — numbered list ────────────── */}
      <section className="shell principles-wrap">
        <motion.header
          className="section-head"
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          <h2 className="section-head-title">
            Four <em>principles</em>, <br />non-negotiable.
          </h2>
          <div className="section-head-meta">
            <span>§ 03 — Working posture</span>
            <span>How we decide, what we ship, what we refuse</span>
          </div>
        </motion.header>

        <ol className="principles">
          {principles.map((p, i) => (
            <motion.li
              key={p.n}
              className="principle"
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.8, delay: i * 0.08, ease: [0.16, 1, 0.3, 1] }}
            >
              <span className="principle-num">{p.n}</span>
              <div className="principle-body">
                <h3 className="principle-title">{p.title}</h3>
                <p className="principle-desc">{p.body}</p>
              </div>
            </motion.li>
          ))}
        </ol>
      </section>

      {/* ── CTA / close ───────────────────────────── */}
      <section className="shell about-close">
        <motion.div
          className="about-close-inner"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
        >
          <div>
            <span className="index-mark">§ 04 — Invitation</span>
            <p className="prose-lg about-close-lede">
              If any of this resonates — the posture, the projects, or
              the refusal to dilute the idea — we'd like to hear from you.
            </p>
          </div>
          <Link to="/contact" className="btn btn-primary">
            Get in touch <span className="btn-arrow">→</span>
          </Link>
        </motion.div>
      </section>

      <footer className="shell colophon">
        <span>Project Odyssey</span>
        <span className="colophon-dot">·</span>
        <span>Studio note — Vol. I</span>
        <span className="colophon-spacer" />
        <span>MMXXVI</span>
      </footer>
    </motion.div>
  )
}
